export default {
  //   //   '24-support': require('./24-support.svg'),
  //   //   '3d-cube-scan': require('./3d-cube-scan.svg'),
  //   //   '3d-rotate': require('./3d-rotate.svg'),
  //   //   '3d-square': require('./3d-square.svg'),
  //   //   '3dcube': require('./3dcube.svg'),
  //   //   '3square': require('./3square.svg'),
  //   //   activity: require('./activity.svg'),
  //   // 'add-circle': require('./add-circle.svg'),
  //   //   'add-square': require('./add-square.svg'),
  //   //   add: require('./add.svg'),
  //   //   additem: require('./additem.svg'),
  //   //   airdrop: require('./airdrop.svg'),
  //   //   'airplane-square': require('./airplane-square.svg'),
  //   //   airplane: require('./airplane.svg'),
  //   //   airpod: require('./airpod.svg'),
  //   //   airpods: require('./airpods.svg'),
  //   //   alarm: require('./alarm.svg'),
  //   //   'align-bottom': require('./align-bottom.svg'),
  //   //   'align-horizontally': require('./align-horizontally.svg'),
  //   //   'align-left': require('./align-left.svg'),
  //   //   'align-right': require('./align-right.svg'),
  //   //   'align-vertically': require('./align-vertically.svg'),
  //   //   aquarius: require('./aquarius.svg'),
  //   //   'archive-1': require('./archive-1.svg'),
  //   //   'archive-2': require('./archive-2.svg'),
  //   //   'archive-add': require('./archive-add.svg'),
  //   //   'archive-book': require('./archive-book.svg'),
  //   'archive-minus': require('./archive-minus.svg'),
  //   //   'archive-slash': require('./archive-slash.svg'),
  //   //   'archive-tick': require('./archive-tick.svg'),
  //   //   archive: require('./archive.svg'),
  //   //   'arrange-circle-2': require('./arrange-circle-2.svg'),
  //   //   'arrange-circle': require('./arrange-circle.svg'),
  //   //   'arrange-square-2': require('./arrange-square-2.svg'),
  //   //   'arrange-square': require('./arrange-square.svg'),
  //   //   'arrow-2': require('./arrow-2.svg'),
  //   //   'arrow-3': require('./arrow-3.svg'),
  //   //   'arrow-bottom': require('./arrow-bottom.svg'),
  'arrow-circle-down': require('./arrow-circle-down.svg'),
  'arrow-circle-left': require('./arrow-circle-left.svg'),
  'arrow-circle-right': require('./arrow-circle-right.svg'),
  'arrow-circle-up': require('./arrow-circle-up.svg'),
  //   //   'arrow-down-1': require('./arrow-down-1.svg'),
  //   //   'arrow-down-2': require('./arrow-down-2.svg'),
  //   'arrow-down': require('./arrow-down.svg'),
  //   //   'arrow-left-1': require('./arrow-left-1.svg'),
  //   //   'arrow-left-2': require('./arrow-left-2.svg'),
  //   //   'arrow-left-3': require('./arrow-left-3.svg'),
  //   //   'arrow-left': require('./arrow-left.svg'),
  //   //   'arrow-right-1': require('./arrow-right-1.svg'),
  //   //   'arrow-right-2': require('./arrow-right-2.svg'),
  //   //   'arrow-right-3': require('./arrow-right-3.svg'),
  //   'arrow-right': require('./arrow-right.svg'),
  //   //   'arrow-square-down': require('./arrow-square-down.svg'),
  //   //   'arrow-square-left': require('./arrow-square-left.svg'),
  //   //   'arrow-square-right': require('./arrow-square-right.svg'),
  //   //   'arrow-square-up': require('./arrow-square-up.svg'),
  //   //   'arrow-square': require('./arrow-square.svg'),
  //   //   'arrow-swap-horizontal': require('./arrow-swap-horizontal.svg'),
  //   //   'arrow-swap': require('./arrow-swap.svg'),
  //   'arrow-up-1': require('./arrow-up-1.svg'),
  //   //   'arrow-up-2': require('./arrow-up-2.svg'),
  //   //   'arrow-up-3': require('./arrow-up-3.svg'),
  //   //   'arrow-up': require('./arrow-up.svg'),
  //   //   arrow: require('./arrow.svg'),
  //   //   'attach-circle': require('./attach-circle.svg'),
  //   //   'attach-square': require('./attach-square.svg'),
  //   //   'audio-square': require('./audio-square.svg'),
  //   //   autobrightness: require('./autobrightness.svg'),
  //   award: require('./award.svg'),
  //   //   'back-square': require('./back-square.svg'),
  //   //   'backward-10-seconds': require('./backward-10-seconds.svg'),
  //   //   'backward-15-seconds': require('./backward-15-seconds.svg'),
  //   //   'backward-5-seconds': require('./backward-5-seconds.svg'),
  //   //   'backward-item': require('./backward-item.svg'),
  //   //   backward: require('./backward.svg'),
  //   //   'bag-2': require('./bag-2.svg'),
  //   //   'bag-cross-1': require('./bag-cross-1.svg'),
  //   //   'bag-cross': require('./bag-cross.svg'),
  //   //   'bag-happy': require('./bag-happy.svg'),
  //   //   'bag-tick-2': require('./bag-tick-2.svg'),
  //   //   'bag-tick': require('./bag-tick.svg'),
  //   //   'bag-timer': require('./bag-timer.svg'),
  //   //   bag: require('./bag.svg'),
  //   //   bank: require('./bank.svg'),
  //   //   barcode: require('./barcode.svg'),
  //   //   'battery-3full': require('./battery-3full.svg'),
  //   //   'battery-charging': require('./battery-charging.svg'),
  //   //   'battery-disable': require('./battery-disable.svg'),
  //   //   'battery-empty-1': require('./battery-empty-1.svg'),
  //   //   'battery-empty': require('./battery-empty.svg'),
  //   //   'battery-full': require('./battery-full.svg'),
  //   //   bezier: require('./bezier.svg'),
  //   //   bill: require('./bill.svg'),
  //   //   'bitcoin-card': require('./bitcoin-card.svg'),
  //   //   'bitcoin-convert': require('./bitcoin-convert.svg'),
  //   //   'bitcoin-refresh': require('./bitcoin-refresh.svg'),
  //   //   'blend-2': require('./blend-2.svg'),
  //   //   blend: require('./blend.svg'),
  //   //   'bluetooth-2': require('./bluetooth-2.svg'),
  //   //   'bluetooth-circle': require('./bluetooth-circle.svg'),
  //   //   'bluetooth-rectangle': require('./bluetooth-rectangle.svg'),
  //   //   bluetooth: require('./bluetooth.svg'),
  //   //   blur: require('./blur.svg'),
  //   'book-1': require('./book-1.svg'),
  //   //   'book-saved': require('./book-saved.svg'),
  //   'book-square': require('./book-square.svg'),
  book: require('./book.svg'),
  //   //   'bookmark-2': require('./bookmark-2.svg'),
  //   //   bookmark: require('./bookmark.svg'),
  //   //   'box-1': require('./box-1.svg'),
  //   //   'box-2': require('./box-2.svg'),
  //   //   'box-add': require('./box-add.svg'),
  //   //   'box-remove': require('./box-remove.svg'),
  //   //   'box-search': require('./box-search.svg'),
  //   //   'box-tick': require('./box-tick.svg'),
  //   //   'box-time': require('./box-time.svg'),
  //   //   box: require('./box.svg'),
  //   //   briefcase: require('./briefcase.svg'),
  //   //   'brifecase-cross': require('./brifecase-cross.svg'),
  //   //   'brifecase-tick': require('./brifecase-tick.svg'),
  //   //   'brifecase-timer': require('./brifecase-timer.svg'),
  //   //   broom: require('./broom.svg'),
  //   //   'brush-1': require('./brush-1.svg'),
  //   //   'brush-2': require('./brush-2.svg'),
  //   //   'brush-3': require('./brush-3.svg'),
  //   //   'brush-4': require('./brush-4.svg'),
  //   //   brush: require('./brush.svg'),
  //   //   bubble: require('./bubble.svg'),
  //   //   'bucket-circle': require('./bucket-circle.svg'),
  //   //   'bucket-square': require('./bucket-square.svg'),
  //   //   bucket: require('./bucket.svg'),
  //   //   'building-3': require('./building-3.svg'),
  //   //   'building-4': require('./building-4.svg'),
  //   //   building: require('./building.svg'),
  //   //   'buildings-2': require('./buildings-2.svg'),
  //   //   buildings: require('./buildings.svg'),
  //   //   buliding: require('./buliding.svg'),
  //   //   bus: require('./bus.svg'),
  //   //   'buy-crypto': require('./buy-crypto.svg'),
  //   //   cake: require('./cake.svg'),
  //   //   calculator: require('./calculator.svg'),
  //   //   'calendar-1': require('./calendar-1.svg'),
  //   'calendar-2': require('./calendar-2.svg'),
  //   //   'calendar-add': require('./calendar-add.svg'),
  //   //   'calendar-circle': require('./calendar-circle.svg'),
  //   //   'calendar-edit': require('./calendar-edit.svg'),
  //   //   'calendar-remove': require('./calendar-remove.svg'),
  //   //   'calendar-search': require('./calendar-search.svg'),
  //   //   'calendar-tick': require('./calendar-tick.svg'),
  //   //   calendar: require('./calendar.svg'),
  //   //   'call-add': require('./call-add.svg'),
  //   //   'call-calling': require('./call-calling.svg'),
  //   //   'call-incoming': require('./call-incoming.svg'),
  //   //   'call-minus': require('./call-minus.svg'),
  //   //   'call-outgoing': require('./call-outgoing.svg'),
  //   //   'call-received': require('./call-received.svg'),
  //   //   'call-remove': require('./call-remove.svg'),
  //   //   'call-slash': require('./call-slash.svg'),
  //   call: require('./call.svg'),
  //   //   'camera-slash': require('./camera-slash.svg'),
  //   //   camera: require('./camera.svg'),
  //   //   'candle-2': require('./candle-2.svg'),
  //   //   candle: require('./candle.svg'),
  //   //   car: require('./car.svg'),
  //   //   'card-add': require('./card-add.svg'),
  //   //   'card-coin': require('./card-coin.svg'),
  //   //   'card-edit': require('./card-edit.svg'),
  //   //   'card-pos': require('./card-pos.svg'),
  //   //   'card-receive': require('./card-receive.svg'),
  //   //   'card-remove-1': require('./card-remove-1.svg'),
  //   //   'card-remove': require('./card-remove.svg'),
  //   //   'card-send': require('./card-send.svg'),
  //   //   'card-slash': require('./card-slash.svg'),
  //   //   'card-tick-1': require('./card-tick-1.svg'),
  //   //   'card-tick': require('./card-tick.svg'),
  //   //   card: require('./card.svg'),
  //   //   cards: require('./cards.svg'),
  //   //   'category-2': require('./category-2.svg'),
  //   //   category: require('./category.svg'),
  //   //   cd: require('./cd.svg'),
  //   //   'chart-1': require('./chart-1.svg'),
  'chart-2': require('./chart-2.svg'),
  //   // 'chart-21': require('./chart-21.svg'),
  //   //   'chart-3': require('./chart-3.svg'),
  //   //   'chart-fail': require('./chart-fail.svg'),
  //   //   'chart-square': require('./chart-square.svg'),
  //   //   'chart-success': require('./chart-success.svg'),
  //   //   chart: require('./chart.svg'),
  //   //   check: require('./check.svg'),
  //   //   chrome: require('./chrome.svg'),
  //   //   'clipboard-close': require('./clipboard-close.svg'),
  //   //   'clipboard-export': require('./clipboard-export.svg'),
  //   //   'clipboard-import': require('./clipboard-import.svg'),
  //   //   'clipboard-text': require('./clipboard-text.svg'),
  //   //   'clipboard-tick': require('./clipboard-tick.svg'),
  //   //   clipboard: require('./clipboard.svg'),
  //   //   'clock-1': require('./clock-1.svg'),
  //   clock: require('./clock.svg'),
  //   'close-circle': require('./close-circle.svg'),
  //   //   'close-square': require('./close-square.svg'),
  //   //   'cloud-add': require('./cloud-add.svg'),
  //   //   'cloud-change': require('./cloud-change.svg'),
  //   //   'cloud-connection': require('./cloud-connection.svg'),
  //   //   'cloud-cross': require('./cloud-cross.svg'),
  //   //   'cloud-drizzle': require('./cloud-drizzle.svg'),
  //   //   'cloud-fog': require('./cloud-fog.svg'),
  //   //   'cloud-lightning': require('./cloud-lightning.svg'),
  //   //   'cloud-minus': require('./cloud-minus.svg'),
  //   //   'cloud-notif': require('./cloud-notif.svg'),
  //   //   'cloud-plus': require('./cloud-plus.svg'),
  //   //   'cloud-remove': require('./cloud-remove.svg'),
  //   //   'cloud-snow': require('./cloud-snow.svg'),
  //   //   'cloud-sunny': require('./cloud-sunny.svg'),
  //   //   cloud: require('./cloud.svg'),
  //   //   'code-1': require('./code-1.svg'),
  //   //   'code-circle': require('./code-circle.svg'),
  //   //   code: require('./code.svg'),
  //   //   coffee: require('./coffee.svg'),
  //   //   'coin-1': require('./coin-1.svg'),
  //   //   coin: require('./coin.svg'),
  //   //   'color-swatch': require('./color-swatch.svg'),
  //   //   colorfilter: require('./colorfilter.svg'),
  //   //   'colors-square': require('./colors-square.svg'),
  //   //   'command-square': require('./command-square.svg'),
  //   //   command: require('./command.svg'),
  //   //   component: require('./component.svg'),
  //   //   computing: require('./computing.svg'),
  //   //   'convert-3d-cube': require('./convert-3d-cube.svg'),
  //   //   'convert-card': require('./convert-card.svg'),
  //   //   convert: require('./convert.svg'),
  //   //   'convertshape-2': require('./convertshape-2.svg'),
  //   //   convertshape: require('./convertshape.svg'),
  //   //   'copy-success': require('./copy-success.svg'),
  //   copy: require('./copy.svg'),
  //   //   copyright: require('./copyright.svg'),
  //   //   courthouse: require('./courthouse.svg'),
  //   //   'cpu-charge': require('./cpu-charge.svg'),
  //   //   'cpu-setting': require('./cpu-setting.svg'),
  //   //   cpu: require('./cpu.svg'),
  //   //   'creative-commons': require('./creative-commons.svg'),
  //   //   crop: require('./crop.svg'),
  //   //   'crown-1': require('./crown-1.svg'),
  //   //   crown: require('./crown.svg'),
  //   cup: require('./cup.svg'),
  //   danger: require('./danger.svg'),
  //   //   'data-2': require('./data-2.svg'),
  //   //   data: require('./data.svg'),
  //   //   designtools: require('./designtools.svg'),
  //   //   'device-message': require('./device-message.svg'),
  //   //   'devices-1': require('./devices-1.svg'),
  //   //   devices: require('./devices.svg'),
  //   //   diagram: require('./diagram.svg'),
  //   //   diamonds: require('./diamonds.svg'),
  //   //   'direct-down': require('./direct-down.svg'),
  //   //   'direct-inbox': require('./direct-inbox.svg'),
  //   //   'direct-left': require('./direct-left.svg'),
  //   //   'direct-normal': require('./direct-normal.svg'),
  //   //   'direct-notification': require('./direct-notification.svg'),
  //   //   'direct-right': require('./direct-right.svg'),
  //   //   'direct-send': require('./direct-send.svg'),
  //   //   'direct-up': require('./direct-up.svg'),
  //   //   direct: require('./direct.svg'),
  //   //   'directbox-default': require('./directbox-default.svg'),
  //   //   'directbox-notif': require('./directbox-notif.svg'),
  //   //   'directbox-receive': require('./directbox-receive.svg'),
  //   //   'directbox-send': require('./directbox-send.svg'),
  //   //   'discount-circle': require('./discount-circle.svg'),
  //   //   'discount-shape': require('./discount-shape.svg'),
  //   //   'discover-1': require('./discover-1.svg'),
  //   // discover: require('./discover.svg'),
  //   //   dislike: require('./dislike.svg'),
  //   //   'document-1': require('./document-1.svg'),
  //   //   'document-cloud': require('./document-cloud.svg'),
  //   //   'document-code-2': require('./document-code-2.svg'),
  //   //   'document-code': require('./document-code.svg'),
  //   //   'document-copy': require('./document-copy.svg'),
  //   'document-download': require('./document-download.svg'),
  //   //   'document-favorite': require('./document-favorite.svg'),
  //   //   'document-filter': require('./document-filter.svg'),
  //   //   'document-forward': require('./document-forward.svg'),
  //   //   'document-like': require('./document-like.svg'),
  //   //   'document-normal': require('./document-normal.svg'),
  //   //   'document-previous': require('./document-previous.svg'),
  //   //   'document-sketch': require('./document-sketch.svg'),
  //   //   'document-text-1': require('./document-text-1.svg'),
  //   'document-text': require('./document-text.svg'),
  //   'document-upload': require('./document-upload.svg'),
  //   //   document: require('./document.svg'),
  //   //   'dollar-circle': require('./dollar-circle.svg'),
  //   //   'dollar-square': require('./dollar-square.svg'),
  //   //   'driver-2': require('./driver-2.svg'),
  //   //   'driver-refresh': require('./driver-refresh.svg'),
  //   //   driver: require('./driver.svg'),
  //   //   driving: require('./driving.svg'),
  //   //   drop: require('./drop.svg'),
  //   'edit-2': require('./edit-2.svg'),
  //   //   edit: require('./edit.svg'),
  //   //   electricity: require('./electricity.svg'),
  //   //   'element-2': require('./element-2.svg'),
  //   //   'element-3': require('./element-3.svg'),
  //   //   'element-4': require('./element-4.svg'),
  //   //   'element-equal': require('./element-equal.svg'),
  //   //   'element-plus': require('./element-plus.svg'),
  //   //   'emoji-happy': require('./emoji-happy.svg'),
  //   //   'emoji-normal': require('./emoji-normal.svg'),
  //   //   'emoji-sad': require('./emoji-sad.svg'),
  //   //   'empty-wallet-add': require('./empty-wallet-add.svg'),
  //   //   'empty-wallet-change': require('./empty-wallet-change.svg'),
  //   //   'empty-wallet-remove': require('./empty-wallet-remove.svg'),
  //   //   'empty-wallet-tick': require('./empty-wallet-tick.svg'),
  //   //   'empty-wallet-time': require('./empty-wallet-time.svg'),
  //   //   'empty-wallet': require('./empty-wallet.svg'),
  //   //   'eraser-1': require('./eraser-1.svg'),
  //   //   eraser: require('./eraser.svg'),
  //   //   'export-1': require('./export-1.svg'),
  //   //   'export-2': require('./export-2.svg'),
  //   'export-3': require('./export-3.svg'),
  //   export: require('./export.svg'),
  //   //   'external-drive': require('./external-drive.svg'),
  'eye-slash': require('./eye-slash.svg'),
  eye: require('./eye.svg'),
  //   //   fatrows: require('./fatrows.svg'),
  //   //   'favorite-chart': require('./favorite-chart.svg'),
  //   //   'filter-add': require('./filter-add.svg'),
  //   //   'filter-edit': require('./filter-edit.svg'),
  //   //   'filter-remove': require('./filter-remove.svg'),
  //   //   'filter-search': require('./filter-search.svg'),
  //   //   'filter-square': require('./filter-square.svg'),
  //   //   'filter-tick': require('./filter-tick.svg'),
  //   //   filter: require('./filter.svg'),
  //   //   'finger-cricle': require('./finger-cricle.svg'),
  //   //   'finger-scan': require('./finger-scan.svg'),
  //   //   firstline: require('./firstline.svg'),
  //   //   'flag-2': require('./flag-2.svg'),
  //   flag: require('./flag.svg'),
  //   //   'flash-1': require('./flash-1.svg'),
  //   //   'flash-circle-1': require('./flash-circle-1.svg'),
  //   //   'flash-circle': require('./flash-circle.svg'),
  //   //   'flash-slash': require('./flash-slash.svg'),
  //   //   flash: require('./flash.svg'),
  //   //   'folder-2': require('./folder-2.svg'),
  //   //   'folder-add': require('./folder-add.svg'),
  //   //   'folder-cloud': require('./folder-cloud.svg'),
  //   //   'folder-connection': require('./folder-connection.svg'),
  //   //   'folder-cross': require('./folder-cross.svg'),
  //   //   'folder-favorite': require('./folder-favorite.svg'),
  //   //   'folder-minus': require('./folder-minus.svg'),
  //   //   'folder-open': require('./folder-open.svg'),
  //   //   folder: require('./folder.svg'),
  //   //   'forbidden-2': require('./forbidden-2.svg'),
  //   //   forbidden: require('./forbidden.svg'),
  //   //   'format-circle': require('./format-circle.svg'),
  //   //   'format-square': require('./format-square.svg'),
  //   //   'forward-10-seconds': require('./forward-10-seconds.svg'),
  //   //   'forward-15-seconds': require('./forward-15-seconds.svg'),
  //   //   'forward-5-seconds': require('./forward-5-seconds.svg'),
  //   //   'forward-item': require('./forward-item.svg'),
  //   //   'forward-square': require('./forward-square.svg'),
  //   //   forward: require('./forward.svg'),
  //   //   'frame-1': require('./frame-1.svg'),
  //   //   'frame-2': require('./frame-2.svg'),
  //   //   'frame-3': require('./frame-3.svg'),
  //   //   'frame-4': require('./frame-4.svg'),
  //   //   frame: require('./frame.svg'),
  //   'gallery-add': require('./gallery-add.svg'),
  //   //   'gallery-edit': require('./gallery-edit.svg'),
  //   //   'gallery-export': require('./gallery-export.svg'),
  //   //   'gallery-favorite': require('./gallery-favorite.svg'),
  //   //   'gallery-import': require('./gallery-import.svg'),
  //   //   'gallery-remove': require('./gallery-remove.svg'),
  //   //   'gallery-slash': require('./gallery-slash.svg'),
  //   //   'gallery-tick': require('./gallery-tick.svg'),
  //   gallery: require('./gallery.svg'),
  //   game: require('./game.svg'),
  //   //   gameboy: require('./gameboy.svg'),
  //   //   'gas-station': require('./gas-station.svg'),
  //   //   'gemini-2': require('./gemini-2.svg'),
  //   //   gemini: require('./gemini.svg'),
  //   //   ghost: require('./ghost.svg'),
  //   gift: require('./gift.svg'),
  //   //   'glass-1': require('./glass-1.svg'),
  //   //   glass: require('./glass.svg'),
  //   //   'global-edit': require('./global-edit.svg'),
  //   //   'global-refresh': require('./global-refresh.svg'),
  //   //   'global-search': require('./global-search.svg'),
  //   global: require('./global.svg'),
  //   //   'gps-slash': require('./gps-slash.svg'),
  //   //   gps: require('./gps.svg'),
  //   //   grammerly: require('./grammerly.svg'),
  //   //   graph: require('./graph.svg'),
  //   //   'grid-1': require('./grid-1.svg'),
  //   //   'grid-2': require('./grid-2.svg'),
  //   //   'grid-3': require('./grid-3.svg'),
  //   //   'grid-4': require('./grid-4.svg'),
  //   //   'grid-5': require('./grid-5.svg'),
  //   //   'grid-6': require('./grid-6.svg'),
  //   //   'grid-7': require('./grid-7.svg'),
  //   //   'grid-8': require('./grid-8.svg'),
  //   //   'grid-9': require('./grid-9.svg'),
  //   //   'grid-edit': require('./grid-edit.svg'),
  //   //   'grid-eraser': require('./grid-eraser.svg'),
  //   //   'grid-lock': require('./grid-lock.svg'),
  //   //   happyemoji: require('./happyemoji.svg'),
  //   //   'hashtag-1': require('./hashtag-1.svg'),
  //   //   'hashtag-down': require('./hashtag-down.svg'),
  //   //   'hashtag-up': require('./hashtag-up.svg'),
  //   //   hashtag: require('./hashtag.svg'),
  //   //   headphone: require('./headphone.svg'),
  //   //   headphones: require('./headphones.svg'),
  //   //   health: require('./health.svg'),
  //   //   'heart-add': require('./heart-add.svg'),
  //   //   'heart-circle': require('./heart-circle.svg'),
  //   //   'heart-edit': require('./heart-edit.svg'),
  //   //   'heart-remove': require('./heart-remove.svg'),
  //   //   'heart-search': require('./heart-search.svg'),
  //   //   'heart-slash': require('./heart-slash.svg'),
  //   //   'heart-tick': require('./heart-tick.svg'),
  heart: require('./heart.svg'),
  //   //   'hierarchy-2': require('./hierarchy-2.svg'),
  //   //   'hierarchy-3': require('./hierarchy-3.svg'),
  //   //   'hierarchy-square-2': require('./hierarchy-square-2.svg'),
  //   //   'hierarchy-square-3': require('./hierarchy-square-3.svg'),
  //   //   'hierarchy-square': require('./hierarchy-square.svg'),
  //   //   hierarchy: require('./hierarchy.svg'),
  'home-1': require('./home-1.svg'),
  //   //   'home-2': require('./home-2.svg'),
  //   //   'home-hashtag': require('./home-hashtag.svg'),
  //   //   'home-trend-down': require('./home-trend-down.svg'),
  //   //   'home-trend-up': require('./home-trend-up.svg'),
  //   //   'home-wifi': require('./home-wifi.svg'),
  //   home: require('./home.svg'),
  //   //   hospital: require('./hospital.svg'),
  //   //   'house-2': require('./house-2.svg'),
  //   //   house: require('./house.svg'),
  //   image: require('./image.svg'),
  //   //   'import-1': require('./import-1.svg'),
  //   //   'import-2': require('./import-2.svg'),
  //   //   'import-3': require('./import-3.svg'),
  //   //   import: require('./import.svg'),
  //   'info-circle': require('./info-circle.svg'),
  //   information: require('./information.svg'),
  //   //   instagram: require('./instagram.svg'),
  //   //   judge: require('./judge.svg'),
  //   //   kanban: require('./kanban.svg'),
  //   //   'key-square': require('./key-square.svg'),
  //   //   key: require('./key.svg'),
  //   //   'keyboard-open': require('./keyboard-open.svg'),
  //   //   keyboard: require('./keyboard.svg'),
  //   //   'lamp-1': require('./lamp-1.svg'),
  //   //   'lamp-charge': require('./lamp-charge.svg'),
  //   //   'lamp-on': require('./lamp-on.svg'),
  //   //   'lamp-slash': require('./lamp-slash.svg'),
  //   //   lamp: require('./lamp.svg'),
  //   //   'language-circle': require('./language-circle.svg'),
  //   //   'language-square': require('./language-square.svg'),
  //   //   layer: require('./layer.svg'),
  //   //   level: require('./level.svg'),
  //   //   lifebuoy: require('./lifebuoy.svg'),
  //   'like-1': require('./like-1.svg'),
  //   //   'like-dislike': require('./like-dislike.svg'),
  //   //   'like-shapes': require('./like-shapes.svg'),
  //   //   'like-tag': require('./like-tag.svg'),
  //   like: require('./like.svg'),
  //   //   'link-1': require('./link-1.svg'),
  //   //   'link-2': require('./link-2.svg'),
  //   //   'link-21': require('./link-21.svg'),
  //   //   'link-circle': require('./link-circle.svg'),
  //   //   'link-square': require('./link-square.svg'),
  //   //   link: require('./link.svg'),
  //   //   'location-add': require('./location-add.svg'),
  //   //   'location-cross': require('./location-cross.svg'),
  //   //   'location-minus': require('./location-minus.svg'),
  //   //   'location-slash': require('./location-slash.svg'),
  //   //   'location-tick': require('./location-tick.svg'),
  //   //   location: require('./location.svg'),
  //   'lock-1': require('./lock-1.svg'),
  //   //   'lock-circle': require('./lock-circle.svg'),
  //   //   'lock-slash': require('./lock-slash.svg'),
  //   lock: require('./lock.svg'),
  //   //   'login-1': require('./login-1.svg'),
  //   //   login: require('./login.svg'),
  //   //   'logout-1': require('./logout-1.svg'),
  //   //   logout: require('./logout.svg'),
  //   //   lovely: require('./lovely.svg'),
  //   'magic-star': require('./magic-star.svg'),
  //   //   magicpen: require('./magicpen.svg'),
  //   //   'main-component': require('./main-component.svg'),
  //   //   man: require('./man.svg'),
  //   //   'map-1': require('./map-1.svg'),
  //   //   map: require('./map.svg'),
  //   //   'mask-1': require('./mask-1.svg'),
  //   //   'mask-2': require('./mask-2.svg'),
  //   //   mask: require('./mask.svg'),
  //   //   math: require('./math.svg'),
  //   //   'maximize-1': require('./maximize-1.svg'),
  //   //   'maximize-2': require('./maximize-2.svg'),
  //   //   'maximize-21': require('./maximize-21.svg'),
  //   //   'maximize-3': require('./maximize-3.svg'),
  //   //   'maximize-4': require('./maximize-4.svg'),
  //   //   'maximize-circle': require('./maximize-circle.svg'),
  //   //   maximize: require('./maximize.svg'),
  //   'medal-star': require('./medal-star.svg'),
  //   medal: require('./medal.svg'),
  //   'menu-1': require('./menu-1.svg'),
  //   //   'menu-board': require('./menu-board.svg'),
  //   //   menu: require('./menu.svg'),
  //   //   'message-2': require('./message-2.svg'),
  //   //   'message-add-1': require('./message-add-1.svg'),
  //   //   'message-add': require('./message-add.svg'),
  //   //   'message-circle': require('./message-circle.svg'),
  //   //   'message-edit': require('./message-edit.svg'),
  //   //   'message-favorite': require('./message-favorite.svg'),
  //   //   'message-minus': require('./message-minus.svg'),
  //   //   'message-notif': require('./message-notif.svg'),
  //   //   'message-programming': require('./message-programming.svg'),
  //   'message-question': require('./message-question.svg'),
  //   //   'message-remove': require('./message-remove.svg'),
  //   //   'message-search': require('./message-search.svg'),
  //   //   'message-square': require('./message-square.svg'),
  //   //   'message-text-1': require('./message-text-1.svg'),
  //   //   'message-text': require('./message-text.svg'),
  //   //   'message-tick': require('./message-tick.svg'),
  //   //   'message-time': require('./message-time.svg'),
  //   //   message: require('./message.svg'),
  //   'messages-1': require('./messages-1.svg'),
  //   //   'messages-2': require('./messages-2.svg'),
  //   //   'messages-3': require('./messages-3.svg'),
  //   //   messages: require('./messages.svg'),
  //   //   'microphone-2': require('./microphone-2.svg'),
  //   //   'microphone-slash-1': require('./microphone-slash-1.svg'),
  //   //   'microphone-slash': require('./microphone-slash.svg'),
  //   //   microphone: require('./microphone.svg'),
  //   //   microscope: require('./microscope.svg'),
  //   //   milk: require('./milk.svg'),
  //   //   'mini-music-sqaure': require('./mini-music-sqaure.svg'),
  //   //   'minus-cirlce': require('./minus-cirlce.svg'),
  //   //   'minus-square': require('./minus-square.svg'),
  //   //   minus: require('./minus.svg'),
  //   //   mirror: require('./mirror.svg'),
  //   //   'mirroring-screen': require('./mirroring-screen.svg'),
  //   //   'mobile-programming': require('./mobile-programming.svg'),
  //   //   mobile: require('./mobile.svg'),
  //   //   'money-2': require('./money-2.svg'),
  //   //   'money-3': require('./money-3.svg'),
  //   //   'money-4': require('./money-4.svg'),
  //   //   'money-add': require('./money-add.svg'),
  //   //   'money-change': require('./money-change.svg'),
  //   //   'money-forbidden': require('./money-forbidden.svg'),
  //   //   'money-recive': require('./money-recive.svg'),
  //   //   'money-remove': require('./money-remove.svg'),
  //   //   'money-send': require('./money-send.svg'),
  //   //   'money-tick': require('./money-tick.svg'),
  //   //   'money-time': require('./money-time.svg'),
  //   //   money: require('./money.svg'),
  //   //   moneys: require('./moneys.svg'),
  //   //   'monitor-mobbile': require('./monitor-mobbile.svg'),
  //   //   'monitor-recorder': require('./monitor-recorder.svg'),
  //   //   monitor: require('./monitor.svg'),
  //   //   moon: require('./moon.svg'),
  //   //   'more-2': require('./more-2.svg'),
  //   //   'more-circle': require('./more-circle.svg'),
  //   //   'more-square': require('./more-square.svg'),
  //   //   more: require('./more.svg'),
  //   //   'mouse-1': require('./mouse-1.svg'),
  //   //   'mouse-circle': require('./mouse-circle.svg'),
  //   //   'mouse-square': require('./mouse-square.svg'),
  //   //   mouse: require('./mouse.svg'),
  //   //   'music-circle': require('./music-circle.svg'),
  //   //   'music-dashboard': require('./music-dashboard.svg'),
  //   //   'music-filter': require('./music-filter.svg'),
  //   //   'music-library-2': require('./music-library-2.svg'),
  //   //   'music-play': require('./music-play.svg'),
  //   //   'music-playlist': require('./music-playlist.svg'),
  //   //   'music-square-add': require('./music-square-add.svg'),
  //   //   'music-square-remove': require('./music-square-remove.svg'),
  //   //   'music-square-search': require('./music-square-search.svg'),
  //   //   'music-square': require('./music-square.svg'),
  //   //   music: require('./music.svg'),
  //   //   musicnote: require('./musicnote.svg'),
  next: require('./next.svg'),
  //   //   'note-1': require('./note-1.svg'),
  //   'note-2': require('./note-2.svg'),
  //   //   'note-21': require('./note-21.svg'),
  //   //   'note-add': require('./note-add.svg'),
  //   //   'note-favorite': require('./note-favorite.svg'),
  //   //   'note-remove': require('./note-remove.svg'),
  //   //   'note-square': require('./note-square.svg'),
  //   'note-text': require('./note-text.svg'),
  //   //   note: require('./note.svg'),
  //   'notification-1': require('./notification-1.svg'),
  //   // 'notification-bing': require('./notification-bing.svg'),
  //   //   'notification-favorite': require('./notification-favorite.svg'),
  //   //   'notification-status': require('./notification-status.svg'),
  //   notification: require('./notification.svg'),
  //   //   'omega-circle': require('./omega-circle.svg'),
  //   //   'omega-square': require('./omega-square.svg'),
  //   //   paintbucket: require('./paintbucket.svg'),
  //   //   'paperclip-2': require('./paperclip-2.svg'),
  //   //   paperclip: require('./paperclip.svg'),
  //   'password-check': require('./password-check.svg'),
  //   password: require('./password.svg'),
  //   //   'path-2': require('./path-2.svg'),
  //   //   'path-square': require('./path-square.svg'),
  //   //   path: require('./path.svg'),
  //   'pause-circle': require('./pause-circle.svg'),
  //   pause: require('./pause.svg'),
  //   //   'pen-add': require('./pen-add.svg'),
  //   //   'pen-close': require('./pen-close.svg'),
  //   //   'pen-remove': require('./pen-remove.svg'),
  //   //   'pen-tool-2': require('./pen-tool-2.svg'),
  //   //   'pen-tool': require('./pen-tool.svg'),
  //   people: require('./people.svg'),
  //   //   'percentage-circle': require('./percentage-circle.svg'),
  //   //   'percentage-square': require('./percentage-square.svg'),
  //   //   personalcard: require('./personalcard.svg'),
  //   //   pet: require('./pet.svg'),
  //   //   pharagraphspacing: require('./pharagraphspacing.svg'),
  //   //   'picture-frame': require('./picture-frame.svg'),
  //   //   'play-add': require('./play-add.svg'),
  //   //   'play-circle': require('./play-circle.svg'),
  //   //   'play-cricle': require('./play-cricle.svg'),
  //   //   'play-remove': require('./play-remove.svg'),
  //   play: require('./play.svg'),
  //   'presention-chart': require('./presention-chart.svg'),
  previous: require('./previous.svg'),
  //   //   'printer-slash': require('./printer-slash.svg'),
  //   //   printer: require('./printer.svg'),
  //   'profile-2user': require('./profile-2user.svg'),
  //   'profile-add': require('./profile-add.svg'),
  //   'profile-circle': require('./profile-circle.svg'),
  //   //   'profile-delete': require('./profile-delete.svg'),
  //   //   'profile-remove': require('./profile-remove.svg'),
  //   'profile-tick': require('./profile-tick.svg'),
  //   //   'programming-arrow': require('./programming-arrow.svg'),
  //   //   'programming-arrows': require('./programming-arrows.svg'),
  //   //   'quote-down-circle': require('./quote-down-circle.svg'),
  //   //   'quote-down-square': require('./quote-down-square.svg'),
  //   //   'quote-down': require('./quote-down.svg'),
  //   //   'quote-up-circle': require('./quote-up-circle.svg'),
  //   //   'quote-up-square': require('./quote-up-square.svg'),
  //   //   'quote-up': require('./quote-up.svg'),
  //   //   'radar-1': require('./radar-1.svg'),
  //   //   'radar-2': require('./radar-2.svg'),
  //   //   radar: require('./radar.svg'),
  //   //   radio: require('./radio.svg'),
  //   //   'ram-2': require('./ram-2.svg'),
  //   //   ram: require('./ram.svg'),
  //   //   'ranking-1': require('./ranking-1.svg'),
  //   ranking: require('./ranking.svg'),
  //   //   'receipt-1': require('./receipt-1.svg'),
  //   //   'receipt-2-1': require('./receipt-2-1.svg'),
  //   //   'receipt-2': require('./receipt-2.svg'),
  //   //   'receipt-add': require('./receipt-add.svg'),
  //   //   'receipt-discount': require('./receipt-discount.svg'),
  //   //   'receipt-disscount': require('./receipt-disscount.svg'),
  //   //   'receipt-edit': require('./receipt-edit.svg'),
  //   //   'receipt-item': require('./receipt-item.svg'),
  //   //   'receipt-minus': require('./receipt-minus.svg'),
  //   //   'receipt-search': require('./receipt-search.svg'),
  //   //   'receipt-square': require('./receipt-square.svg'),
  //   //   'receipt-text': require('./receipt-text.svg'),
  //   //   receipt: require('./receipt.svg'),
  //   //   'receive-square-2': require('./receive-square-2.svg'),
  //   //   'receive-square': require('./receive-square.svg'),
  //   //   received: require('./received.svg'),
  //   //   'record-circle': require('./record-circle.svg'),
  //   //   record: require('./record.svg'),
  //   //   'recovery-convert': require('./recovery-convert.svg'),
  //   //   redo: require('./redo.svg'),
  //   //   'refresh-2': require('./refresh-2.svg'),
  //   //   'refresh-circle': require('./refresh-circle.svg'),
  //   //   'refresh-left-square': require('./refresh-left-square.svg'),
  //   //   'refresh-right-square': require('./refresh-right-square.svg'),
  //   //   'refresh-square-2': require('./refresh-square-2.svg'),
  //   //   refresh: require('./refresh.svg'),
  //   //   'repeat-circle': require('./repeat-circle.svg'),
  //   //   repeat: require('./repeat.svg'),
  //   //   'repeate-music': require('./repeate-music.svg'),
  //   //   'repeate-one': require('./repeate-one.svg'),
  //   //   reserve: require('./reserve.svg'),
  //   //   'rotate-left-1': require('./rotate-left-1.svg'),
  //   //   'rotate-left': require('./rotate-left.svg'),
  //   //   'rotate-right-1': require('./rotate-right-1.svg'),
  //   //   'rotate-right': require('./rotate-right.svg'),
  //   //   'route-square': require('./route-square.svg'),
  //   //   'routing-2': require('./routing-2.svg'),
  //   //   routing: require('./routing.svg'),
  //   //   'row-horizontal': require('./row-horizontal.svg'),
  //   //   'row-vertical': require('./row-vertical.svg'),
  //   //   'ruler&pen': require('./ruler&pen.svg'),
  //   //   ruler: require('./ruler.svg'),
  //   //   'safe-home': require('./safe-home.svg'),
  //   //   sagittarius: require('./sagittarius.svg'),
  //   'save-2': require('./save-2.svg'),
  //   'save-add': require('./save-add.svg'),
  //   'save-minus': require('./save-minus.svg'),
  //   'save-remove': require('./save-remove.svg'),
  //   'scan-barcode': require('./scan-barcode.svg'),
  //   scan: require('./scan.svg'),
  //   scanner: require('./scanner.svg'),
  //   scanning: require('./scanning.svg'),
  //   //   'scissor-1': require('./scissor-1.svg'),
  //   //   scissor: require('./scissor.svg'),
  //   //   screenmirroring: require('./screenmirroring.svg'),
  //   //   scroll: require('./scroll.svg'),
  //   'search-favorite-1': require('./search-favorite-1.svg'),
  //   //   'search-favorite': require('./search-favorite.svg'),
  //   'search-normal-1': require('./search-normal-1.svg'),
  //   'search-normal': require('./search-normal.svg'),
  //   //   'search-status-1': require('./search-status-1.svg'),
  //   //   'search-status': require('./search-status.svg'),
  //   //   'search-zoom-in-1': require('./search-zoom-in-1.svg'),
  //   //   'search-zoom-in': require('./search-zoom-in.svg'),
  //   //   'search-zoom-out-1': require('./search-zoom-out-1.svg'),
  //   //   'search-zoom-out': require('./search-zoom-out.svg'),
  //   //   'security-card': require('./security-card.svg'),
  //   'security-safe': require('./security-safe.svg'),
  //   //   'security-time': require('./security-time.svg'),
  //   'security-user': require('./security-user.svg'),
  //   //   security: require('./security.svg'),
  //   //   'send-1': require('./send-1.svg'),
  //   'send-2': require('./send-2.svg'),
  //   //   'send-sqaure-2': require('./send-sqaure-2.svg'),
  //   //   'send-square': require('./send-square.svg'),
  //   //   send: require('./send.svg'),
  'setting-2': require('./setting-2.svg')
  //   //   'setting-3': require('./setting-3.svg'),
  //   //   'setting-4': require('./setting-4.svg'),
  //   //   'setting-5': require('./setting-5.svg'),
  //   setting: require('./setting.svg'),
  //   //   settings: require('./settings.svg'),
  //   //   'shapes-1': require('./shapes-1.svg'),
  //   //   shapes: require('./shapes.svg'),
  //   share: require('./share.svg'),
  //   //   'shield-cross': require('./shield-cross.svg'),
  //   //   'shield-search': require('./shield-search.svg'),
  //   //   'shield-security': require('./shield-security.svg'),
  //   //   'shield-slash': require('./shield-slash.svg'),
  //   //   'shield-tick': require('./shield-tick.svg'),
  //   //   ship: require('./ship.svg'),
  //   //   'shop-add': require('./shop-add.svg'),
  //   //   'shop-remove': require('./shop-remove.svg'),
  //   //   shop: require('./shop.svg'),
  //   //   'shopping-bag': require('./shopping-bag.svg'),
  //   //   'shopping-cart': require('./shopping-cart.svg'),
  //   //   shuffle: require('./shuffle.svg'),
  //   //   'sidebar-bottom': require('./sidebar-bottom.svg'),
  //   //   'sidebar-left': require('./sidebar-left.svg'),
  //   //   'sidebar-right': require('./sidebar-right.svg'),
  //   //   'sidebar-top': require('./sidebar-top.svg'),
  //   //   signpost: require('./signpost.svg'),
  //   //   'simcard-1': require('./simcard-1.svg'),
  //   //   'simcard-2': require('./simcard-2.svg'),
  //   //   simcard: require('./simcard.svg'),
  //   //   size: require('./size.svg'),
  //   //   slash: require('./slash.svg'),
  //   //   'slider-horizontal-1': require('./slider-horizontal-1.svg'),
  //   //   'slider-horizontal': require('./slider-horizontal.svg'),
  //   //   'slider-vertical-1': require('./slider-vertical-1.svg'),
  //   //   'slider-vertical': require('./slider-vertical.svg'),
  //   //   slider: require('./slider.svg'),
  //   //   smallcaps: require('./smallcaps.svg'),
  //   //   'smart-car': require('./smart-car.svg'),
  //   //   'smart-home': require('./smart-home.svg'),
  //   //   smileys: require('./smileys.svg'),
  //   //   'sms-edit': require('./sms-edit.svg'),
  //   //   'sms-notification': require('./sms-notification.svg'),
  //   //   'sms-search': require('./sms-search.svg'),
  //   //   'sms-star': require('./sms-star.svg'),
  //   //   'sms-tracking': require('./sms-tracking.svg'),
  //   //   sms: require('./sms.svg'),
  //   //   sort: require('./sort.svg'),
  //   //   sound: require('./sound.svg'),
  //   //   speaker: require('./speaker.svg'),
  //   //   speedometer: require('./speedometer.svg'),
  //   //   'star-1': require('./star-1.svg'),
  //   //   'star-slash': require('./star-slash.svg'),
  //   star: require('./star.svg'),
  //   'star-2': require('./star-2.svg'),
  //   'star-3': require('./star-3.svg'),
  //   //   'status-up': require('./status-up.svg'),
  //   //   status: require('./status.svg'),
  //   //   sticker: require('./sticker.svg'),
  //   //   stickynote: require('./stickynote.svg'),
  //   //   'stop-circle': require('./stop-circle.svg'),
  //   stop: require('./stop.svg'),
  //   //   story: require('./story.svg'),
  //   //   'strongbox-2': require('./strongbox-2.svg'),
  //   //   strongbox: require('./strongbox.svg'),
  //   //   subtitle: require('./subtitle.svg'),
  //   //   'sun-1': require('./sun-1.svg'),
  //   //   'sun-fog': require('./sun-fog.svg'),
  //   //   sun: require('./sun.svg'),
  //   //   'tag-2': require('./tag-2.svg'),
  //   //   'tag-cross': require('./tag-cross.svg'),
  //   //   'tag-right': require('./tag-right.svg'),
  //   'tag-user': require('./tag-user.svg'),
  //   //   tag: require('./tag.svg'),
  //   'task-square': require('./task-square.svg'),
  //   //   task: require('./task.svg'),
  //   teacher: require('./teacher.svg'),
  //   //   'text-block': require('./text-block.svg'),
  //   //   'text-bold': require('./text-bold.svg'),
  //   //   'text-italic': require('./text-italic.svg'),
  //   //   'text-underline': require('./text-underline.svg'),
  //   //   text: require('./text.svg'),
  //   //   'textalign-center': require('./textalign-center.svg'),
  //   //   'textalign-justifycenter': require('./textalign-justifycenter.svg'),
  //   //   'textalign-justifyleft': require('./textalign-justifyleft.svg'),
  //   //   'textalign-justifyright': require('./textalign-justifyright.svg'),
  //   //   'textalign-left': require('./textalign-left.svg'),
  //   //   'textalign-right': require('./textalign-right.svg'),
  //   'tick-circle': require('./tick-circle.svg'),
  //   'tick-square': require('./tick-square.svg'),
  //   //   'ticket-2': require('./ticket-2.svg'),
  //   //   'ticket-discount': require('./ticket-discount.svg'),
  //   //   'ticket-expired': require('./ticket-expired.svg'),
  //   //   'ticket-star': require('./ticket-star.svg'),
  //   //   ticket: require('./ticket.svg'),
  //   'timer-1': require('./timer-1.svg'),
  //   'timer-pause': require('./timer-pause.svg'),
  //   //   'timer-start': require('./timer-start.svg'),
  //   timer: require('./timer.svg'),
  //   //   'toggle-off-circle': require('./toggle-off-circle.svg'),
  //   //   'toggle-off': require('./toggle-off.svg'),
  //   //   'toggle-on-circle': require('./toggle-on-circle.svg'),
  //   //   'toggle-on': require('./toggle-on.svg'),
  //   //   trade: require('./trade.svg'),
  //   //   'transaction-minus': require('./transaction-minus.svg'),
  //   //   translate: require('./translate.svg'),
  //   trash: require('./trash.svg'),
  //   //   tree: require('./tree.svg'),
  //   //   'trend-down': require('./trend-down.svg'),
  //   //   'trend-up': require('./trend-up.svg'),
  //   //   triangle: require('./triangle.svg'),
  //   //   'truck-fast': require('./truck-fast.svg'),
  //   //   'truck-remove': require('./truck-remove.svg'),
  //   //   'truck-tick': require('./truck-tick.svg'),
  //   //   'truck-time': require('./truck-time.svg'),
  //   //   truck: require('./truck.svg'),
  //   //   'trush-square': require('./trush-square.svg'),
  //   //   undo: require('./undo.svg'),
  //   //   unlimited: require('./unlimited.svg'),
  //   //   unlock: require('./unlock.svg'),
  //   'user-add': require('./user-add.svg'),
  //   'user-cirlce-add': require('./user-cirlce-add.svg'),
  //   //   'user-edit': require('./user-edit.svg'),
  //   //   'user-minus': require('./user-minus.svg'),
  //   'user-octagon': require('./user-octagon.svg'),
  //   //   'user-remove': require('./user-remove.svg'),
  //   //   'user-search': require('./user-search.svg'),
  //   'user-square': require('./user-square.svg'),
  //   'user-tag': require('./user-tag.svg'),
  //   'user-tick': require('./user-tick.svg'),
  //   user: require('./user.svg'),
  //   verify: require('./verify.svg'),
  //   //   'video-add': require('./video-add.svg'),
  //   //   'video-circle': require('./video-circle.svg'),
  //   //   'video-horizontal': require('./video-horizontal.svg'),
  //   //   'video-octagon': require('./video-octagon.svg'),
  //   //   'video-play': require('./video-play.svg'),
  //   //   'video-remove': require('./video-remove.svg'),
  //   //   'video-slash': require('./video-slash.svg'),
  //   'video-square': require('./video-square.svg'),
  //   //   'video-tick': require('./video-tick.svg'),
  //   //   'video-time': require('./video-time.svg'),
  //   //   'video-vertical': require('./video-vertical.svg'),
  //   //   video: require('./video.svg'),
  //   //   'voice-cricle': require('./voice-cricle.svg'),
  //   //   'voice-square': require('./voice-square.svg'),
  //   'volume-cross': require('./volume-cross.svg'),
  //   'volume-high': require('./volume-high.svg'),
  //   //   'volume-low-1': require('./volume-low-1.svg'),
  //   //   'volume-low': require('./volume-low.svg'),
  //   //   'volume-mute': require('./volume-mute.svg'),
  //   //   'volume-slash': require('./volume-slash.svg'),
  //   //   'volume-up': require('./volume-up.svg'),
  //   //   'wallet-1': require('./wallet-1.svg'),
  //   //   'wallet-2': require('./wallet-2.svg'),
  //   //   'wallet-3': require('./wallet-3.svg'),
  //   //   'wallet-add-1': require('./wallet-add-1.svg'),
  //   //   'wallet-add': require('./wallet-add.svg'),
  //   //   'wallet-check': require('./wallet-check.svg'),
  //   //   'wallet-minus': require('./wallet-minus.svg'),
  //   //   'wallet-money': require('./wallet-money.svg'),
  //   //   'wallet-remove': require('./wallet-remove.svg'),
  //   //   'wallet-search': require('./wallet-search.svg'),
  //   //   wallet: require('./wallet.svg'),
  //   'warning-2': require('./warning-2.svg'),
  //   //   'watch-status': require('./watch-status.svg'),
  //   //   watch: require('./watch.svg'),
  //   //   'weight-1': require('./weight-1.svg'),
  //   //   weight: require('./weight.svg'),
  //   //   'wifi-square': require('./wifi-square.svg'),
  //   //   wifi: require('./wifi.svg'),
  //   //   'wind-2': require('./wind-2.svg'),
  //   //   wind: require('./wind.svg'),
  //   //   woman: require('./woman.svg'),
  //   'more-horizontal': require('./more-horizontal.svg'),
  //   'more-vertical': require('./more-vertical.svg'),
  //   true: require('./true.svg'),
  //   false: require('./false.svg'),
  //   back: require('./back.svg'),
  //   plus: require('./plus.svg'),
  //   close: require('./close.svg'),
  //   apple: require('./apple.svg'),
  //   google: require('./google.svg'),
  //   facebook: require('./facebook.svg'),
  //   question: require('./question.svg'),
  //   tick: require('./tick.svg'),
  //   'menu-list': require('./menu-list.svg'),
  //   down: require('./down.svg'),
  //   up: require('./up.svg'),
}
